---
# tasks file for create_install_config

- name: Get Base64 Encoded Token for Local Registry
  shell:
    cmd: echo -n "{{ htpasswd_docker_user }}":"{{ htpasswd_docker_password }}"| base64 -w0
  register: localtoken


- name: display multiple file contents
  shell:
    cmd: "cat /opt/registry/certs/ca.crt|grep -v CERTIFICATE| tr -d '\n'"
  register: cert

- name: Create install-config.yaml template - Disconnected
  template:
    src: templates/install-config.yaml.j2
    dest: "{{ artifact_dir }}/install-config.yaml"
  when: disconnected=true

- name: Create install-config.yaml template - Connected
  template:
    src: templates/install-config-connected.yaml.j2
    dest: "{{ artifact_dir }}/install-config.yaml"
  when: disconnected=false
